create table tpcc..stock (
		    s_i_id          int,
		    s_w_id          smallint,
		    s_quantity      smallint,
		    s_dist_01       char(24),
		    s_dist_02       char(24),
		    s_dist_03       char(24),
		    s_dist_04       char(24),
		    s_dist_05       char(24),
		    s_dist_06       char(24),
		    s_dist_07       char(24),
		    s_dist_08       char(24),
		    s_dist_09       char(24),
		    s_dist_10       char(24),
		    s_ytd           int,
		    s_cnt_order     smallint,
		    s_cnt_remote    smallint,
		    s_data          char(50) )
